sudo: required
language: android
jdk: oraclejdk7

services:
  - docker

env:
  matrix:
  - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
#  - ANDROID_TARGET=android-14  ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.2
    - android-21
    - extra-android-m2repository

before_install:
  - docker build -t blazsolar/android .
  - docker run -d -p 127.0.0.1:80:4567 blazsolar/android /bin/sh -c "cd /root/root; bundle exec foreman start;"
  - docker ps -a
  - docker run blazsolar/android /bin/sh -c "cd /root/root; bundle exec rake test"
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - ./gradlew check
  - ./gradlew connectedCheck
  - ./gradlew installDebug
  - adb shell monkey -p com.github.blazsolar.chuck -v 10000

after_success:
  - ./gradlew coveralls
