FORMAT: 1A

# Chuck Norris
Jokes API is a mock vrsion of http://www.icndb.com/api/.

# Group Jokes
Jokes endponts

## Random Joke [/jokes/random]
A single Joke with all its data

### Retrieve a Joke [GET]
+ Response 200 (application/json)

    + Body

            { "type": "success", "value": { "id": 268, "joke": "Some random Chuck Norris joke from mock server." } }

